<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>obfy</AssemblyName>

    <Version>1.0.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Obfy.Console.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Obfy.Core\Obfy.Core.csproj" />
    <ProjectReference Include="..\Logging.Core\Logging.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.2.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
  </ItemGroup>

</Project>
