using System.Text;
using Microsoft.Extensions.Logging;
using Obfy.Core.Models;

namespace Obfy.Core.Services.Reporting;

/// <summary>
/// Generates HTML format obfuscation reports with visual styling.
/// </summary>
public class HtmlReportGenerator : IReportGenerator
{
    private readonly ILogger<HtmlReportGenerator> _logger;

    /// <summary>
    /// Creates a new HTML report generator.
    /// </summary>
    public HtmlReportGenerator(ILogger<HtmlReportGenerator> logger)
    {
        _logger = logger;
    }

    /// <inheritdoc/>
    public string FileExtension => ".html";

    /// <inheritdoc/>
    public async Task GenerateAsync(ObfuscationReport report, string outputPath, CancellationToken cancellationToken = default)
    {
        var html = await GenerateToStringAsync(report, cancellationToken);

        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllTextAsync(outputPath, html, cancellationToken);
        _logger.LogInformation("HTML report written to {OutputPath}", outputPath);
    }

    /// <inheritdoc/>
    public Task<string> GenerateToStringAsync(ObfuscationReport report, CancellationToken cancellationToken = default)
    {
        var sb = new StringBuilder();

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("  <meta charset=\"UTF-8\">");
        sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"  <title>Obfuscation Report - {Path.GetFileName(report.FileInfo.InputPath)}</title>");
        sb.AppendLine(GetStyles());
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header
        sb.AppendLine("  <header>");
        sb.AppendLine("    <h1>Obfuscation Report</h1>");
        sb.AppendLine($"    <p class=\"subtitle\">Generated by Obfy v{report.Metadata.ObfyVersion}</p>");
        sb.AppendLine("  </header>");

        sb.AppendLine("  <main>");

        // Summary section
        GenerateSummarySection(sb, report);

        // File info section
        GenerateFileInfoSection(sb, report);

        // Statistics section
        GenerateStatisticsSection(sb, report);

        // Symbol summary section
        GenerateSymbolSummarySection(sb, report);

        // Settings section
        GenerateSettingsSection(sb, report);

        // Processing times section
        GenerateProcessingTimesSection(sb, report);

        // Warnings section
        GenerateWarningsSection(sb, report);

        sb.AppendLine("  </main>");

        // Footer
        sb.AppendLine("  <footer>");
        sb.AppendLine($"    <p>Report generated at {report.Metadata.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC</p>");
        sb.AppendLine("  </footer>");

        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return Task.FromResult(sb.ToString());
    }

    private static string GetStyles()
    {
        return @"<style>
    :root {
        --primary-color: #0078d4;
        --success-color: #107c10;
        --warning-color: #ffb900;
        --error-color: #d13438;
        --info-color: #0078d4;
        --bg-color: #f5f5f5;
        --card-bg: #ffffff;
        --text-color: #323130;
        --text-secondary: #605e5c;
        --border-color: #e1e1e1;
    }
    * { box-sizing: border-box; }
    body {
        font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
        background: var(--bg-color);
        color: var(--text-color);
        margin: 0;
        padding: 20px;
        line-height: 1.5;
    }
    header {
        text-align: center;
        margin-bottom: 30px;
        padding: 20px;
        background: linear-gradient(135deg, var(--primary-color), #005a9e);
        color: white;
        border-radius: 8px;
    }
    header h1 { margin: 0 0 5px 0; font-weight: 600; }
    .subtitle { margin: 0; opacity: 0.9; }
    main { max-width: 1200px; margin: 0 auto; }
    .card {
        background: var(--card-bg);
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .card h2 {
        margin: 0 0 15px 0;
        padding-bottom: 10px;
        border-bottom: 2px solid var(--primary-color);
        font-size: 1.2em;
        font-weight: 600;
    }
    .stats-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
        gap: 15px;
    }
    .stat-item {
        text-align: center;
        padding: 15px;
        background: var(--bg-color);
        border-radius: 6px;
    }
    .stat-value {
        font-size: 2em;
        font-weight: bold;
        color: var(--primary-color);
    }
    .stat-value.highlight {
        color: var(--success-color);
    }
    .stat-label {
        color: var(--text-secondary);
        font-size: 0.85em;
        margin-top: 5px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
    }
    th, td {
        text-align: left;
        padding: 10px 12px;
        border-bottom: 1px solid var(--border-color);
    }
    th {
        background: var(--bg-color);
        font-weight: 600;
    }
    tr:last-child td { border-bottom: none; }
    .badge {
        display: inline-block;
        padding: 3px 10px;
        border-radius: 12px;
        font-size: 0.85em;
        font-weight: 500;
    }
    .badge.enabled {
        background: #dff6dd;
        color: var(--success-color);
    }
    .badge.disabled {
        background: #f3f2f1;
        color: var(--text-secondary);
    }
    .warning-item {
        padding: 12px 15px;
        margin: 8px 0;
        border-radius: 4px;
        border-left: 4px solid;
    }
    .warning-item.info {
        background: #deecf9;
        border-color: var(--info-color);
    }
    .warning-item.warning {
        background: #fff4ce;
        border-color: var(--warning-color);
    }
    .warning-item.important {
        background: #fde7e9;
        border-color: var(--error-color);
    }
    .warning-item .category {
        font-size: 0.75em;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        opacity: 0.7;
        margin-bottom: 4px;
    }
    .size-change {
        font-weight: 600;
    }
    .size-change.positive { color: var(--error-color); }
    .size-change.negative { color: var(--success-color); }
    .size-change.neutral { color: var(--text-secondary); }
    footer {
        text-align: center;
        padding: 20px;
        color: var(--text-secondary);
        font-size: 0.85em;
    }
    .no-data {
        color: var(--text-secondary);
        font-style: italic;
    }
</style>";
    }

    private static void GenerateSummarySection(StringBuilder sb, ObfuscationReport report)
    {
        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>Summary</h2>");
        sb.AppendLine("      <table>");
        sb.AppendLine($"        <tr><td>Input File</td><td>{Path.GetFileName(report.FileInfo.InputPath)}</td></tr>");
        sb.AppendLine($"        <tr><td>Obfuscation Level</td><td>{report.Metadata.Level}</td></tr>");
        sb.AppendLine($"        <tr><td>Total Duration</td><td>{report.Metadata.TotalElapsedTime:mm\\:ss\\.fff}</td></tr>");
        sb.AppendLine($"        <tr><td>Total Transformations</td><td><strong>{report.Statistics.TotalTransformations:N0}</strong></td></tr>");
        sb.AppendLine("      </table>");
        sb.AppendLine("    </div>");
    }

    private static void GenerateFileInfoSection(StringBuilder sb, ObfuscationReport report)
    {
        var sizeChangeClass = report.FileInfo.SizeDifferenceBytes switch
        {
            > 0 => "positive",
            < 0 => "negative",
            _ => "neutral"
        };

        var sizeChangeSign = report.FileInfo.SizeDifferenceBytes >= 0 ? "+" : "";

        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>File Information</h2>");
        sb.AppendLine("      <table>");
        sb.AppendLine($"        <tr><td>Input Path</td><td>{report.FileInfo.InputPath}</td></tr>");
        sb.AppendLine($"        <tr><td>Output Path</td><td>{report.FileInfo.OutputPath}</td></tr>");
        sb.AppendLine($"        <tr><td>Input Size</td><td>{FormatBytes(report.FileInfo.InputSizeBytes)}</td></tr>");
        sb.AppendLine($"        <tr><td>Output Size</td><td>{FormatBytes(report.FileInfo.OutputSizeBytes)}</td></tr>");
        sb.AppendLine($"        <tr><td>Size Change</td><td><span class=\"size-change {sizeChangeClass}\">{sizeChangeSign}{FormatBytes(report.FileInfo.SizeDifferenceBytes)} ({sizeChangeSign}{report.FileInfo.SizeChangePercent:F1}%)</span></td></tr>");
        sb.AppendLine("      </table>");
        sb.AppendLine("    </div>");
    }

    private static void GenerateStatisticsSection(StringBuilder sb, ObfuscationReport report)
    {
        var stats = report.Statistics;

        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>Transformation Statistics</h2>");
        sb.AppendLine("      <div class=\"stats-grid\">");

        AddStatItem(sb, stats.StringsEncrypted, "Strings Encrypted");
        AddStatItem(sb, stats.ConstantsEncrypted, "Constants Encrypted");
        AddStatItem(sb, stats.ResourcesEncrypted, "Resources Encrypted");
        AddStatItem(sb, stats.TypesRenamed, "Types Renamed");
        AddStatItem(sb, stats.MethodsRenamed, "Methods Renamed");
        AddStatItem(sb, stats.FieldsRenamed, "Fields Renamed");
        AddStatItem(sb, stats.PropertiesRenamed, "Properties Renamed");
        AddStatItem(sb, stats.ParametersRenamed, "Parameters Renamed");
        AddStatItem(sb, stats.MethodsControlFlowObfuscated, "Control Flow");
        AddStatItem(sb, stats.ProtectionsApplied, "Protections");
        AddStatItem(sb, stats.MetadataItemsRemoved, "Metadata Removed");
        AddStatItem(sb, stats.TotalTransformations, "Total", highlight: true);

        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
    }

    private static void AddStatItem(StringBuilder sb, int value, string label, bool highlight = false)
    {
        var valueClass = highlight ? "stat-value highlight" : "stat-value";
        sb.AppendLine($"        <div class=\"stat-item\"><div class=\"{valueClass}\">{value:N0}</div><div class=\"stat-label\">{label}</div></div>");
    }

    private static void GenerateSymbolSummarySection(StringBuilder sb, ObfuscationReport report)
    {
        var summary = report.SymbolSummary;

        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>Symbol Renaming Summary</h2>");
        sb.AppendLine("      <table>");
        sb.AppendLine($"        <tr><td>Naming Mode</td><td>{summary.NamingModeUsed}</td></tr>");
        sb.AppendLine($"        <tr><td>Total Symbols Renamed</td><td>{summary.TotalSymbolsRenamed:N0}</td></tr>");
        sb.AppendLine($"        <tr><td>Types</td><td>{summary.TypesRenamed:N0}</td></tr>");
        sb.AppendLine($"        <tr><td>Methods</td><td>{summary.MethodsRenamed:N0}</td></tr>");
        sb.AppendLine($"        <tr><td>Fields</td><td>{summary.FieldsRenamed:N0}</td></tr>");
        sb.AppendLine($"        <tr><td>Properties</td><td>{summary.PropertiesRenamed:N0}</td></tr>");
        sb.AppendLine($"        <tr><td>Parameters</td><td>{summary.ParametersRenamed:N0}</td></tr>");
        sb.AppendLine("      </table>");
        sb.AppendLine("    </div>");
    }

    private static void GenerateSettingsSection(StringBuilder sb, ObfuscationReport report)
    {
        var settings = report.SettingsUsed;

        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>Settings Used</h2>");
        sb.AppendLine("      <table>");

        AddSettingRow(sb, "String Encryption", settings.StringEncryptionEnabled);
        AddSettingRow(sb, "Constant Encryption", settings.ConstantEncryptionEnabled);
        AddSettingRow(sb, "Resource Encryption", settings.ResourceEncryptionEnabled);
        AddSettingRow(sb, "Control Flow Obfuscation", settings.ControlFlowEnabled);
        AddSettingRow(sb, "Symbol Renaming", settings.SymbolRenamingEnabled);
        AddSettingRow(sb, "Anti-Debug Protection", settings.AntiDebugEnabled);
        AddSettingRow(sb, "Metadata Removal", settings.MetadataRemovalEnabled);
        AddSettingRow(sb, "Preserve Public API", settings.PreservePublicApi);

        sb.AppendLine("      </table>");
        sb.AppendLine("    </div>");
    }

    private static void AddSettingRow(StringBuilder sb, string name, bool enabled)
    {
        var badgeClass = enabled ? "badge enabled" : "badge disabled";
        var badgeText = enabled ? "Enabled" : "Disabled";
        sb.AppendLine($"        <tr><td>{name}</td><td><span class=\"{badgeClass}\">{badgeText}</span></td></tr>");
    }

    private static void GenerateProcessingTimesSection(StringBuilder sb, ObfuscationReport report)
    {
        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>Processing Times</h2>");

        if (report.ProcessingTimes.Count == 0)
        {
            sb.AppendLine("      <p class=\"no-data\">No timing data available.</p>");
        }
        else
        {
            sb.AppendLine("      <table>");
            sb.AppendLine("        <tr><th>Obfuscator</th><th>Duration</th><th>Transformations</th></tr>");

            foreach (var entry in report.ProcessingTimes)
            {
                sb.AppendLine($"        <tr><td>{entry.ObfuscatorName}</td><td>{entry.Duration.TotalMilliseconds:F0}ms</td><td>{entry.TransformationsApplied:N0}</td></tr>");
            }

            sb.AppendLine("      </table>");
        }

        sb.AppendLine("    </div>");
    }

    private static void GenerateWarningsSection(StringBuilder sb, ObfuscationReport report)
    {
        sb.AppendLine("    <div class=\"card\">");
        sb.AppendLine("      <h2>Warnings</h2>");

        if (report.Warnings.Count == 0)
        {
            sb.AppendLine("      <p class=\"no-data\">No warnings generated.</p>");
        }
        else
        {
            foreach (var warning in report.Warnings)
            {
                var severityClass = warning.Severity.ToString().ToLowerInvariant();
                sb.AppendLine($"      <div class=\"warning-item {severityClass}\">");
                sb.AppendLine($"        <div class=\"category\">{warning.Category}</div>");
                sb.AppendLine($"        <div>{warning.Message}</div>");
                if (!string.IsNullOrEmpty(warning.Details))
                {
                    sb.AppendLine($"        <div style=\"margin-top:5px;font-size:0.9em;opacity:0.8;\">{warning.Details}</div>");
                }
                sb.AppendLine("      </div>");
            }
        }

        sb.AppendLine("    </div>");
    }

    private static string FormatBytes(long bytes)
    {
        var absBytes = Math.Abs(bytes);
        string[] suffixes = { "B", "KB", "MB", "GB" };
        var suffixIndex = 0;
        var size = (double)absBytes;

        while (size >= 1024 && suffixIndex < suffixes.Length - 1)
        {
            size /= 1024;
            suffixIndex++;
        }

        var formatted = size < 10 ? $"{size:F2}" : size < 100 ? $"{size:F1}" : $"{size:F0}";
        return $"{(bytes < 0 ? "-" : "")}{formatted} {suffixes[suffixIndex]}";
    }
}
